### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by Elitalak** [GCodeProjects/GCodeWorkShop#22]
Wold it be possible to add code so that drag and drop files into the editor could work?

**Comment by u-235** [comment]
Hi.

Thanks for the wonderful idea.

A basic implementation is not difficult to do, but simple solutions are not always user friendly. The application needs to be able to detect the type of files being dragged and prompt the user for confirmation in cases of unsuitable types. And this can take some time.

I've made a basic drag-n-drop implementation that opens all dropped files, and you can test it on the [drag-n-drop branch](https://github.com/u-235/edytornc/tree/drag-n-drop).

**Comment by Elitalak** [comment]
This works great! 
I am only going to drag and drop known nc-programs.
Thanks for your fast response, i will test it more in the upcoming  week and get back with feedback.

**Comment by Elitalak** [comment]
Hello!
i have been testing this drag-n-drop for almost a week now and i am very happy with how it works.

**Comment by u-235** [comment]
I'm still thinking of doing a simple filtering by file extension. The list of extensions is available in the settings and is also used in the open file dialog.

**Comment by u-235** [comment]
completed at https://github.com/GCodeProjects/GCodeWorkShop/releases/tag/2024-05
