### ISSUE TITLE
Releases for Linux

### ISSUE THREAD

**Issue by MatthewReed303** [GCodeProjects/GCodeWorkShop#28]
Hi @u-235  

I managed to build on Ubuntu 22.04 after quite a few issues. In the future would it be possible to also release DEB packages along with the EXE

The main issue is QT5 Default is not supported in the later distros, so maybe if we can move to QT6? Would make the process more simple

If anyone comes across this and try to run on new distro please install the following:

```
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qttools5-dev-tools libqt5serialport5-dev
```

**Comment by u-235** [comment]
Hi.

As you rightly point out, the build instructions need to be updated. But for now it is not a priority. Linux installation packages are also planned, but most likely this will not happen before October.

It is possible to use Qt6 now, but I have not tested such builds yet. To build an application with Qt6 you need to install the following packages:

```sh
apt install qmake6 qt6-base-dev-tools qt6-l10n-tools qt6-base-dev qt6-serialport-dev qt6-5compat-dev
```

**Comment by u-235** [comment]
done  
https://github.com/GCodeProjects/GCodeWorkShop/releases/tag/2024-09
