### ISSUE TITLE
BUG: saving a file smaller than existing file doesn't truncate the file

### ISSUE THREAD

**Issue by zmaile** [GCodeProjects/GCodeWorkShop#37]
Installer: gcodeworkshop-2024-09_ubuntu-noble_amd64.deb 
OS: Linux Mint 22.0

When I edit a file, remove some text, and overwrite it, the file on disk does not shrink. The new file data is intact at the start of the file, however the existing contents of the end of the larger file remain.

**Comment by u-235** [comment]
Hi.
Thanks for the bug report. As it was checked, that bug is present on windows as well. I will try to fix it soon.

**Comment by u-235** [comment]
I think [the new release](https://github.com/GCodeProjects/GCodeWorkShop/releases/tag/2024-10) fixes this.
